### ISSUE TITLE
Exception creating GRPC client

### ISSUE THREAD

**Issue by malafeev** [lightstep/lightstep-tracer-java#122]
version `0.12.10`
Looks like something wrong, but nothing in the output with verbosity 4:
```
2017-08-17 22:18:33.254 ERROR   [main] com.lightstep.tracer.jre.JRETracer:printLogToConsole:56 - Exception creating GRPC client.
2017-08-17 22:18:33.260 INFO   [main] com.lightstep.tracer.jre.JRETracer:printLogToConsole:50 - Disabling client library
``` 

project: https://github.com/malafeev/rxjava-feign-hystrix-failure
test: https://github.com/malafeev/rxjava-feign-hystrix-failure/blob/master/src/test/java/io/opentracing/contrib/rxjava_feign/LightStepTest.java#L49

I've set my Access Token

**Comment by frenchfrywpepper** [comment]
Since 0.12.7 you need to include GRPC and Netty in your pom. Something like...

```xml
<dependency>
      <groupId>io.grpc</groupId>
      <artifactId>grpc-netty</artifactId>
      <version>1.4.0</version>
</dependency>
<dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty-tcnative-boringssl-static</artifactId>
      <version>2.0.5.Final</version>
</dependency>
```
This was briefly noted in the [CHANGELOG](https://github.com/lightstep/lightstep-tracer-java/blob/master/CHANGELOG.md), but could probably be made more transparent. Let me know if you have suggestions on how to better manage that.

**Comment by malafeev** [comment]
Please add it to README.md
